# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(name: "restaurants")
Category.create(name: "wine")
Category.create(name: "plant")
Category.create(name: "housewares")
Category.create(name: "bars")
Category.create(name: "coffee")
Category.create(name: "yoga")
Category.create(name: "gyms")
Category.create(name: "bookstores")
Category.create(name: "health stores")
Category.create(name: "pets")

Shop.create(category_id: 1, name: "Barcito Bodega", description: "Argentinian-style eatery featuring an amazing natural wine and beer selection", social_impact: "Particpates in High Road Kitchens, a new initiative that aims to fund independent restaurants while feeding low-wage workers and first responders.", address: "403 W 12th St, Los Angeles, CA 90015", website: "barcitola.com")
Shop.create(category_id: 1, name: "Honey Hi", description: "Honey Hi feature sunstainably-sourced, high-quality ingredients from local LA farmers", social_impact: "", address: "1620 Sunset Blvd, Los Angeles, CA 90026", website: "honeyhi.co")
Shop.create(category_id: 6, name: "VanillaBlack Coffee", description: "Small coffee shop located in Echo Park", social_impact: "", address: "1825 Sunset Blvd Los Angeles, California 90026", website: "vanillablack.square.site")
Shop.create(category_id: 1, name: "Beyond Vegan", description: "Boyle Heights-based vegan restaurant", social_impact: '', address: , website: 'beyondveganlifestyle.com')
Shop.create(category_id: 1, name: "Chicken N Chips", description: "Chicken n Chips is the #1 chicken restaurant in LA. Serving oven roasted NAE chicken, fresh potato fries, made from scratch stuffing and gravies. An Australia style of serving rotisserie chicken right in LA", social_impact: '', address: '2728 Fletcher Dr, Los Angeles, CA 90039', website: 'chickennchips.com')
Shop.create(category_id: 10, name: "The Juice", description: "A Neighborhood Juice & Smoothie Shop. Serving 100% Organic Cold Pressed Juice and Smoothies", social_impact: '', address: '3145 Glendale Blvd, Los Angeles, CA 90039', website:  'thejuicela.com')
Shop.create(category_id: 9, name: "Eso Won Books", description: 'Eso Won provides fluid, safe, stirring opportunities that flow to a reservoir of knowledge for all people to experience.', social_impact: '', address: '4327 Degnan Blvd, Los Angeles, CA 90008'. website:  'esowonbookstore.com')
Shop.create(category_id: 9, name: 'Malik Books', description: , social_impact: , address: '3650 W Martin Luther King Jr Blvd, Los Angeles, CA 90008', website:  'malikbooks.com')
Shop.create(category_id: 9, name: "Reparations Club", description: 'Rep Club is a concept (book)shop & creative space curated by Blackness in Los Angeles, CA. Black-owned. Woman-owned.', social_impact: '', address: '3054 S. Victoria Ave. Los Angeles, CA 90016', website: 'rep.club',)
Shop.create(category_id: 10, name: "SUPRMRKT", description: 'SÜPRMARKT is a low cost organic grocery servicing low income communities in LA. It operates weekly, providing 100% organic produce to make great health and healing available to the communities which need it most', social_impact: 'Provides low-cost, high-quality produce to low-income communities', address: 'Check the website for the next location of SUPRMRKT', website: 'suprmarkt.la')
Shop.create(category_id: 10, name: 'Thrive Health Lab', description: 'Thrive aims to encourage and empower communities through education, proactive programming, and holistic wellness.', social_impact: '', address: '3701 West 54th St, Los Angeles, California 90043', website: 'thrivehealthlab.com')
Shop.create(category_id: 6, name: 'Boketto Cold Brew', description:'Boketto has teamed up with some of North America’s best Roasters and Sommeliers as they travel the world in search of sustainably farmed Artisan teas and coffees.' , social_impact: , address:'743 S Broadway, Los Angeles, CA 90014', website:'bokettocoldbrew.com')
Shop.create(category_id: 6, name: 'Coffee by Kofi', description: 'Downtown LA coffee shop', social_impact: , address: '1933 South Broadway Lobby, Los Angeles, CA 90007', website: 'coffeebykofi.com' )
Shop.create(category_id: 1, name: 'SugarJones', description: 'Sugar Jones makes truly delicious desserts. Moist cakes, chewy cookies and fudgy brownies are just the beginning.', social_impact: , address: 'Los Angeles, CA 91607', website: 'sweetsugarjones.com')
Shop.create(category_id: 1, name: 'Comfort LA', description: 'ComfortLA started as a late-night, pop-up restaurant taking a clean approach to soul food. They use locally sourced, fresh and organic ingredients and healthier cooking methods to create top-notch, Southern cuisine.', social_impact: , address: '1110 E 7th Street, Los Angeles, CA 90021', website: 'https://www.eatcomfortla.com/')
Shop.create(category_id: 1, name: 'Funculo', description: 'Build Your own Pasta Bowl Bar Starting with a choice of a wide variety of Pastas Following Freshly made Sauce Ending with Unlimited Toppings.', social_impact: , address: '724 S Spring St, Los Angeles, CA 90014', website:  'https://downtownla.com/go/funculo')
Shop.create(category_id: 1, name: 'Woodspoon', description: 'Stylish but simple Brazilian spot known for yuca fries & chicken pot pies paired with sangria.', social_impact: , address: '107 W 9th St, Los Angeles, CA 90015'website: 'http://www.woodspoonla.com/')
Shop.create(category_id: 1, name: 'Barbara Jean Soul Food', description: 'Barbara Jean Restaurant is a celebration of American Soul Food. A cuisine that is imbued with the many cultures that make up this vast and diverse country.', social_impact: , address: '3939 S Figueroa St, Los Angeles, CA 90037', website:  'http://barbarajeanla.com/')
Shop.create(category_id: 1, name: 'BLUDSO’S BAR & QUE', description: 'Born in Compton, raised by Texas', social_impact: , address: '609 North La Brea Avenue, Los Angeles, CA, 90036', website: 'https://www.barandque.com/')
Shop.create(category_id: 1, name: "Big Ant's BBQ", description: "Big Ant's BBQ started in 1987 in Louisiana, in the backwoods of the country. Founded by Papa Hypolite, the tradition now carries on through his son, Big Ant (short for Anthony).", social_impact: , address: '2207 N San Fernando Rd, Los Angeles, CA, 90065', website: 'https://www.bigantsbbq.com/'  )
Shop.create(category_id: 6, name: 'Hilltop Coffee + Kitchen', description: "'We take pride in creating fun environments for people to connect with each other and themselves. We’re young and ambitious, climbing our own Hilltops personally and professionally, just like everyone else.' ", social_impact: , address: '4427 W. Slauson Avenue, Los Angeles, CA 90043', website: 'findyourhilltop.com')
Shop.create(category_id: 1, name: 'Roscoes Chicken and Waffles', description: 'World famous chicken and waffles', social_impact: , address: '1514 N Gower St, Los Angeles, CA, 90028', website: 'https://www.roscoeschickenandwaffles.com/')
Shop.create(category_id: 1, name: 'Buna Ethiopian Restaurant & Market', description: 'Buna Ethiopian Restaurant & Market is sizzlin’ with delicious artisanal cooking and brewing fresh coffee from Ethiopia – all this is wrapped in the tradition of music and culture of a continent halfway across the world, yet embedded in the heart of its owners and operators Eyob and Helena. ', social_impact: , address: '1034 S Fairfax Ave, Los Angeles, CA 90019', website: 'https://bunaethiopianmarket.com/')
Shop.create(category_id: 1, name: 'Meals by Genet', description: 'Located in the heart of Little Ethiopia, we strive to bring you the best of the vibrant, traditional cuisine of Ethiopia in a casual bistro setting. In addition to the restaurant, we offer full service catering, specializing in private parties, weddings, corporate events and more.', social_impact: , address: '1053 S. Fairfax Ave., Los Angeles, CA 90019', website: 'http://mealsbygenetla.com')
Shop.create(category_id: 1, name: 'Rosalinds', description: 'Pioneering Ethopian restaurant, one of the first in Little Ethiopia.', social_impact: , address: '1044 S. Fairfax, Los Angeles, CA 90019', website: 'https://rosalindsla.com/')
Shop.create(category_id: 6, name: 'Little Amsterdam Coffee', description: 'Art, Coffee, and Music in One Cup', social_impact: , address: '1412 S Redondo Blvd, Los Angeles, CA 90019', website: 'littleamsterdamcoffee.net')
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )
Shop.create(category_id: , name: , description: , social_impact: , address: , website: )



Tag.create(name: "BIPOC-OWNED")
Tag.create(name: "WOMEN/WOMXN-OWNED")
Tag.create(name: "LGBTQ+-OWNED")
Tag.create(name: "SOCIAL IMPACT COMMITMENT")

ShopTag.create(shop_id: 1, tag_id: 2)
ShopTag.create(shop_id: 1, tag_id: 4)
ShopTag.create(shop_id: 2, tag_id: 2)
ShopTag.create(shop_id: 3, tag_id: 1)
ShopTag.create(shop_id: 4, tag_id: 1)
ShopTag.create(shop_id: 5, tag_id: 1)
ShopTag.create(shop_id: 6, tag_id: 1)
ShopTag.create(shop_id: 6, tag_id: 2)
ShopTag.create(shop_id: 7, tag_id: 1)
ShopTag.create(shop_id: 8, tag_id: 1)
ShopTag.create(shop_id: 9, tag_id: 1)
ShopTag.create(shop_id: 9, tag_id: 2)
ShopTag.create(shop_id: 10, tag_id: 1)
ShopTag.create(shop_id: 10, tag_id: 2)
ShopTag.create(shop_id: 10, tag_id: 4)
ShopTag.create(shop_id: 11, tag_id: 1)
ShopTag.create(shop_id: 12, tag_id: 1)
ShopTag.create(shop_id: 13, tag_id: 1)
ShopTag.create(shop_id: 14, tag_id: 1)
ShopTag.create(shop_id: 15, tag_id: 1)
ShopTag.create(shop_id: 16, tag_id: 1)
ShopTag.create(shop_id: 17, tag_id: 1)
ShopTag.create(shop_id: 18, tag_id: 1)
ShopTag.create(shop_id: 19, tag_id: 1)
ShopTag.create(shop_id: 20, tag_id: 1)
ShopTag.create(shop_id: 21, tag_id: 1)
ShopTag.create(shop_id: 22, tag_id: 1)
ShopTag.create(shop_id: 23, tag_id: 1)
ShopTag.create(shop_id: 24, tag_id: 1)
ShopTag.create(shop_id: 24, tag_id: 2)
ShopTag.create(shop_id: 25, tag_id: 1)
ShopTag.create(shop_id: 25, tag_id: 2)
ShopTag.create(shop_id: 26, tag_id: 1)
ShopTag.create(shop_id: 27, tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)
ShopTag.create(shop_id: , tag_id: 1)



